"""Entry point for the OpenAI input-token counting demo.

Usage:
    python -m token_count_demo.main
    python -m token_count_demo.main --model gpt-5
    python -m token_count_demo.main --case tools
    python -m token_count_demo.main --json
"""

import argparse
import json
import sys

from .client import get_client
from .cases import build_cases

# ── Rich is optional; fall back to plain text if not installed ──────────────
try:
    from rich.console import Console
    from rich.table import Table
    from rich import print as rprint
    _RICH = True
    console = Console()
except ImportError:
    _RICH = False
    console = None  # type: ignore[assignment]


# ── Delta comparisons ────────────────────────────────────────────────────────
# Each entry is (label, case_name_a, case_name_b).
# The delta shown is  b.input_tokens − a.input_tokens.
DELTA_PAIRS = [
    ("instructions overhead", "simple_text", "instructions"),
    ("tool schema overhead", "weather_no_tools", "weather_with_tools"),
    ("RAG context overhead", "simple_text", "rag_context"),
]

CLOSING_NOTE = (
    "\nNote: This endpoint counts input tokens only — before the model runs.\n"
    "It does NOT predict:\n"
    "  • output tokens generated by the model\n"
    "  • token cost of future agent steps or loop iterations\n"
    "  • tool-call results that have not yet been added to the conversation\n"
    "  • retries, re-plans, or additional retrieval rounds\n"
    "\nFor agents, total cost requires summing every model call plus generated\n"
    "output, tool results, retrieved documents, and repeated loop steps."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Count OpenAI input tokens across different payload types."
    )
    parser.add_argument(
        "--model",
        default="gpt-5",
        help="Model name to pass to the token counting endpoint (default: gpt-5)",
    )
    parser.add_argument(
        "--case",
        default=None,
        metavar="CASE_NAME",
        help="Run only this case (by name slug). Omit to run all cases.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output raw JSON instead of a table",
    )
    return parser.parse_args()


def count_tokens(client, payload: dict) -> int:
    """Call the input token counting endpoint and return the count."""
    response = client.responses.input_tokens.count(**payload)
    return response.input_tokens


def run_cases(client, cases: list[dict]) -> list[dict]:
    """Run each case and return a list of result dicts."""
    results = []
    for case in cases:
        try:
            tokens = count_tokens(client, case["payload"])
            results.append({
                "name": case["name"],
                "description": case["description"],
                "input_tokens": tokens,
                "error": None,
            })
        except Exception as exc:
            results.append({
                "name": case["name"],
                "description": case["description"],
                "input_tokens": None,
                "error": str(exc),
            })
    return results


def compute_deltas(results: list[dict]) -> list[dict]:
    """Compute delta rows based on DELTA_PAIRS."""
    by_name = {r["name"]: r for r in results}
    deltas = []
    for label, name_a, name_b in DELTA_PAIRS:
        row_a = by_name.get(name_a)
        row_b = by_name.get(name_b)
        if (
            row_a and row_b
            and row_a["input_tokens"] is not None
            and row_b["input_tokens"] is not None
        ):
            deltas.append({
                "label": label,
                "from": name_a,
                "to": name_b,
                "delta": row_b["input_tokens"] - row_a["input_tokens"],
            })
    return deltas


# ── Output helpers ───────────────────────────────────────────────────────────

def print_table_rich(results: list[dict], deltas: list[dict]) -> None:
    table = Table(title="OpenAI Input Token Counts", show_lines=True)
    table.add_column("Case", style="cyan", no_wrap=True)
    table.add_column("Description", style="white")
    table.add_column("Input Tokens", justify="right", style="green")

    for r in results:
        tokens = (
            str(r["input_tokens"])
            if r["input_tokens"] is not None
            else f"[red]ERROR: {r['error']}[/red]"
        )
        table.add_row(r["name"], r["description"], tokens)

    console.print(table)

    if deltas:
        delta_table = Table(title="Token Delta Comparisons", show_lines=True)
        delta_table.add_column("What adds tokens", style="cyan")
        delta_table.add_column("Baseline case", style="dim")
        delta_table.add_column("Compared case", style="dim")
        delta_table.add_column("Δ tokens", justify="right", style="yellow")

        for d in deltas:
            delta_table.add_row(d["label"], d["from"], d["to"], f"+{d['delta']}")

        console.print(delta_table)

    console.print(CLOSING_NOTE)


def print_table_plain(results: list[dict], deltas: list[dict]) -> None:
    sep = "-" * 78
    header = f"{'Case':<22} {'Input Tokens':>13}  Description"
    print("\nOpenAI Input Token Counts")
    print(sep)
    print(header)
    print(sep)
    for r in results:
        if r["input_tokens"] is not None:
            tokens_str = str(r["input_tokens"])
        else:
            tokens_str = f"ERROR"
        print(f"{r['name']:<22} {tokens_str:>13}  {r['description']}")
        if r["error"]:
            print(f"  {'':22}  └─ {r['error']}")
    print(sep)

    if deltas:
        print("\nToken Delta Comparisons")
        print(sep)
        print(f"{'What adds tokens':<28} {'Baseline':<22} {'Compared':<24} Δ")
        print(sep)
        for d in deltas:
            print(
                f"{d['label']:<28} {d['from']:<22} {d['to']:<24} +{d['delta']}"
            )
        print(sep)

    print(CLOSING_NOTE)


def print_json(results: list[dict], deltas: list[dict]) -> None:
    output = {"results": results, "deltas": deltas}
    print(json.dumps(output, indent=2))


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()
    client = get_client()

    all_cases = build_cases(args.model)

    # Filter to a single case if requested
    if args.case:
        filtered = [c for c in all_cases if c["name"] == args.case]
        if not filtered:
            available = ", ".join(c["name"] for c in all_cases)
            sys.exit(
                f"Unknown case '{args.case}'.\nAvailable cases: {available}"
            )
        cases_to_run = filtered
    else:
        cases_to_run = all_cases

    results = run_cases(client, cases_to_run)
    deltas = compute_deltas(results) if not args.case else []

    if args.json_output:
        print_json(results, deltas)
    elif _RICH:
        print_table_rich(results, deltas)
    else:
        print_table_plain(results, deltas)


if __name__ == "__main__":
    main()
